[package]
name = "xdp-screencast"
version = "0.1.0"
edition = "2024"
authors = ["dlzht"]

[dependencies]
bitflags = "2.9"
zbus = { version = "5", default-features = false, features = ["tokio"] }

[dev-dependencies]
tokio = { version = "1" , features = [ "rt", "macros" ]}